### PR TITLE
Updated base16 themes

### PR DESCRIPTION
**Pull request by ShiromMakkad**
We've got 110 new themes!

It looks like the base16 themes haven't been updated in 5 years, and base16 has tripled in size since then. There were also 30 themes that got updated. 

Solves #243

### CODE REVIEW

**Comment by chrisbra** [comment]
Uff, that is a lot. Does it really make sense to integrate all of those? 

Can you please fix those warnings and add the new themes to the documentation please (along with some configuration switches, if those exists, I suppose not). Perhaps, it would also be nice, to add a small section in the help on how those base16 themes have been generated. Thanks!

**Comment by ShiromMakkad** [comment]
I can add the themes to the docs, but regarding how I made the themes, these themes were generated using the templates here: https://github.com/fnurl/base16-vim-airline/blob/master/templates/default.mustache. This is your official repository that base16 links to, and it's used to keep your base16 themes up to date. Unfortunately, it hasn't been used in 4 years; that's why so many themes were added. All of these themes have active maintainers and were approved by Chris Kempson, the official maintainer of Base16. I can link to detailed instructions on generating the themes in the wiki. 

Regarding the warnings, they're about using single quotes rather than double quotes, but I built the themes from the official theme template. I could modify the theme template locally and rebuild the themes, but the base16 themes would no longer follow the official template, which I feel is even more unclear than using single quotes instead of double quotes. I think the best solution is to get the maintainer of that repository to update the template officially with the styling you want and the configuration switches you mentioned.

**Comment by chrisbra** [comment]
okay, thanks. Then please add a short section in the help and how to update the generated themes. I think then we are ready to include this.
Thanks!

**Comment by endorama** [comment]
Hello, would be awesome to see this included! Any way I could help with this?

**Comment by ShiromMakkad** [comment]
@endorama Honestly, I forgot about this PR. I can write the short section in the help without a problem, but I've been procrastinating on creating a formatted list of all the base16 themes for the `doc/airline-themes.txt` file. If you can help with that, I can make the changes pretty quickly. If not, I should be free to finish this up within a couple weeks.

**Comment by chrisbra** [comment]
> procrastinating on creating a formatted list of all the base16 themes for the doc/airline-themes.txt

Not sure I understand. That should be pretty easy with some vim magic. First remove all themes starting with base16 from the help page. Then do a `:r! ls -1 ../autoload/airline/themes/base16*.vim` That should insert all base16 themes below. Then just shift the lines and add the star using e.g. visual block mode insert or something.

**Comment by endorama** [comment]
@ShiromMakkad I can't push to this branch, so I don't know how I could help. 

Based on your help text I'm willing to provide another PR automating the themes update & the docs, if the maintainer is interested with that.

**Comment by ShiromMakkad** [comment]
> Then do a :r! ls -1 ../autoload/airline/themes/base16*.vim That should insert all base16 themes below. 

....and I was going to make Python script for this. I've got a lot to learn about Vim

**Comment by chrisbra** [comment]
can you please fix the vint warnings? And please squash into a single commit. I think then we are fine.

**Comment by ShiromMakkad** [comment]
For the warnings,

> Regarding the warnings, they're about using single quotes rather than double quotes, but I built the themes from the official theme template. I could modify the theme template locally and rebuild the themes, but the base16 themes would no longer follow the official template, which I feel is even more unclear than using single quotes instead of double quotes. I think the best solution is to get the maintainer of that repository to update the template officially with the styling you want and the configuration switches you mentioned.

I had some issues squashing the commits into one, but I think it's good to go.

**Comment by chrisbra** [comment]
what's the reason for messing with the CI scripts?

**Pull request closed without merging**
