### PR TITLE
Add deus theme to doc

### PR DESCRIPTION
**Pull request by fbearoff**
I've modified @ajmwagar's branch and added deus to doc/airline-themes.txt as requested in pull request #92

### CODE REVIEW

**Comment by chrisbra** [comment]
Thanks. Can you please squash?

**Comment by fbearoff** [comment]
Should be good now, squashed those 4 commits to 1

**Comment by chrisbra** [comment]
thanks

**Comment by assistcontrol** [comment]
Is there something missing from this commit?

I get "The specified theme cannot be found." The `deus.vim` file certainly looks quite different from all the other theme files.

**Comment by chrisbra** [comment]
Yeah, it was in dos mode. I fixed it and adjusted it slightly.

**Pull request merged**
