### PR TITLE
Add gruvbox theme

### PR DESCRIPTION
**Pull request by jsatk**
Taken from the official gruvbox repo. https://github.com/morhetz/gruvbox/blob/master/autoload/airline/themes/gruvbox.vim

### CODE REVIEW

**Comment by chrisbra** [comment]
why do we need it here, if it is included with the gruvbox colorscheme?

**Comment by jsatk** [comment]
So people don’t need to know about and also install a separate plugin just to get one colorscheme. I love having all my colorschemes in one place and from one plugin.

**Comment by chrisbra** [comment]
I am not sure I understand. To be able to use the gruvbox colorscheme, people need to install the [gruvbox plugin](https://github.com/morhetz/gruvbox) (which includes a theme for vim-airline). Now we can of course copy the vim-airline theme here, but there are a couple of issues I like to mention:
 - people would still need to install the gruvbox plugin, because just using the gruvbox airline theme does not make much sense 
- how do we keep the themes in sync if we start to distribute it in two different projects?

**Comment by jsatk** [comment]
@chrisbra you're totally right. Oversight on my part. Thanks for clarifying. I'll close.

**Comment by kazukazuinaina** [comment]
What happened to this issue?

**Pull request closed without merging**
