### PR TITLE
Add jet theme

### PR DESCRIPTION
**Pull request by cryptarch**
A dark theme with soft colours.

I've been using this theme for nearly two years and find it very nice to use. Maybe others will enjoy it as well.

screenshot

### CODE REVIEW

**Comment by chrisbra** [comment]
please squash in the change to the documentation. Thanks.

**Comment by cryptarch** [comment]
I think I just did, let me know if I've misunderstood what you mean

**Comment by chrisbra** [comment]
yes thanks. However, I'd like to have only a single commit, which includes the documentation, which is commonly called squashing. You might simply do a git rebase -i HEAD~2 and for the last commit change the pick to squash. That should leave your project with a single commit containing all your changes you can then simply force push them to your github branch and the PR will then look clean.

Thanks for considering.

**Comment by cryptarch** [comment]
Ah, I see. Hopefully this will be better now.

**Comment by chrisbra** [comment]
thanks, great!

**Pull request merged**
