### PR TITLE
molokai: Fix color behaviour with replace mode

### PR DESCRIPTION
**Pull request by mimadrid**
Before
before

After
after

And better contrast between replace an visual modes
Before
before_replace
before_visual

After
after_replace
after_visual

### CODE REVIEW

**Comment by mimadrid** [comment]
Finished, and sorry.

**Comment by mimadrid** [comment]
Perhaps visual mode better with 118 (green)?

**Comment by chrisbra** [comment]
thanks. Please squash.

**Comment by mimadrid** [comment]
I changed finally to green the visual mode and I forgot to update gui colors.
Thanks a lot.

**Comment by chrisbra** [comment]
okay, thanks again.

**Pull request merged**
