### PR TITLE
Add base 16 gruvbox dark hard to the themes

### PR DESCRIPTION
**Pull request by ronald2wing**

### CODE REVIEW

**Comment by chrisbra** [comment]
okay thanks! Just add a line to doc/airline-themes.txt and mention this theme.

**Comment by ronald2wing** [comment]
Just add the theme in the doc

**Comment by chrisbra** [comment]
thanks. I have merged it.

**Comment by ronald2wing** [comment]
> thanks. I have merged it.

This is the most productive thing I did in this month.

**Comment by chrisbra** [comment]
great for motivating. 👍

**Pull request closed without merging**
