### PR TITLE
Cobalt 2 theme

### PR DESCRIPTION
**Pull request by g-kanoufi**
Hi guys, i have added a adaptation of Wes Bos Cobalt 2 theme to airline, hope this will go through the pull request.

I also have a screenshot, but have no idea where to add it.

Cheers,

Guillaume

### CODE REVIEW

**Comment by ryanoasis** [comment]
> I also have a screenshot, but have no idea where to add it.

I believe you are supposed to add in a comment for the PR then after merged to the vim airline wiki

**Comment by chrisbra** [comment]
Yes, please add the screenshot, thanks!

**Comment by g-kanoufi** [comment]
Hi guys sorry about that, but i am still not sure on how to add the screenshot to the wiki, forking vim-airline, i have no idea where to find the wiki page... So for now, here is a link to it: https://lostwebdesigns.com/content/uploads/2016/08/vim-airline-cobalt2-1.jpg

Thanks.

**Comment by chrisbra** [comment]
Am 2016-08-25 09:57, schrieb Guillaume Kanoufi:
> Hi guys sorry about that, but i am still not sure on how to add the
> screenshot to the wiki, forking vim-airline, i have no idea where to
> find the wiki page... So for now, here is a link to it:
> https://lostwebdesigns.com/content/uploads/2016/08/vim-airline-cobalt2-1.jpg
> 
> 
> Thanks.

It's a wiki, so you can easily edit 
https://github.com/vim-airline/vim-airline/wiki/Screenshots
yourself.

**Comment by g-kanoufi** [comment]
Alright, i was not sure about editing it myself :)

Will try to do that today.

Thank you



---

Guillaume Kanoufi / Web developer  
g.kanoufi@gmail.com
https://lostwebdesigns.com

                


On August 25, 2016 at 10:56:48, Christian Brabandt (notifications@github.com) wrote:

Am 2016-08-25 09:57, schrieb Guillaume Kanoufi:
> Hi guys sorry about that, but i am still not sure on how to add the
> screenshot to the wiki, forking vim-airline, i have no idea where to
> find the wiki page... So for now, here is a link to it:
> https://lostwebdesigns.com/content/uploads/2016/08/vim-airline-cobalt2-1.jpg
>
>
> Thanks.

It's a wiki, so you can easily edit
https://github.com/vim-airline/vim-airline/wiki/Screenshots
yourself.

**Comment by g-kanoufi** [comment]
Ok, it’s all set.

Thank you, cheers!



---

Guillaume Kanoufi / Web developer  
g.kanoufi@gmail.com
https://lostwebdesigns.com

                


On August 25, 2016 at 10:56:48, Christian Brabandt (notifications@github.com) wrote:

Am 2016-08-25 09:57, schrieb Guillaume Kanoufi:
> Hi guys sorry about that, but i am still not sure on how to add the
> screenshot to the wiki, forking vim-airline, i have no idea where to
> find the wiki page... So for now, here is a link to it:
> https://lostwebdesigns.com/content/uploads/2016/08/vim-airline-cobalt2-1.jpg
>
>
> Thanks.

It's a wiki, so you can easily edit
https://github.com/vim-airline/vim-airline/wiki/Screenshots
yourself.

**Pull request merged**
