### PR TITLE
[contrib] Added alduin.vim colorscheme

### PR DESCRIPTION
**Pull request by danilo-augusto**
99fd192a-ee71-11e6-833b-11abeeebca82
9a23375e-ee71-11e6-9110-20ad3b819884
9a1ff94a-ee71-11e6-8758-f5fd900b6686

### CODE REVIEW

**Comment by chrisbra** [comment]
please at least mention it in the documentation.

**Comment by danilo-augusto** [comment]
Done. Sorry about that.

**Comment by bearcatsandor** [comment]
I'm eagerly awaiting this merge.

**Comment by chrisbra** [comment]
please squash and I'll merge

**Comment by chrisbra** [comment]
any update here?

**Comment by bearcatsandor** [comment]
I'm not sure why the OP seems to have abandoned it, but is there anything i can do to get this finished?

**Comment by danilo-augusto** [comment]
@chrisbra  Sorry for the delay, for some reason I have not received the notification of your previous message (about squashing). It's done: squashed into one commit and ready to merge.

**Comment by chrisbra** [comment]
thanks.

**Pull request merged**
