### PR TITLE
Port NightOwl Theme

### PR DESCRIPTION
**Pull request by jaredramirez**
screen shot 2018-07-28 at 11 27 20
screen shot 2018-07-28 at 11 27 59
screen shot 2018-07-28 at 11 26 45
screen shot 2018-07-28 at 11 28 26

### CODE REVIEW

**Comment by chrisbra** [comment]
Missing part in the documentation. Also please squash into a single commit.

**Comment by jaredramirez** [comment]
Hey, squashed and added in screenshots to https://github.com/vim-airline/vim-airline-themes/issues/1

**Comment by chrisbra** [comment]
still missing a mention in the documentation :(

**Comment by jaredramirez** [comment]
Sorry about that, didn't see that part of the contribution section. Completely my bad. I've added a reference to this theme in the documentation.

**Comment by chrisbra** [comment]
thanks.

**Pull request merged**
