### PR TITLE
update colours for both Ubaryd and Laederon themes

### PR DESCRIPTION
**Pull request by Donearm**
version updating for both themes

### CODE REVIEW

**Comment by chrisbra** [comment]
why are those colors changed?

**Comment by Donearm** [comment]
I've tweaked the airline theme to match better the original ViM theme and to fix high contrast occasions that previously made the airline themes not so nice to stare at

**Comment by chrisbra** [comment]
hm, Should that be made configurable?

**Comment by Donearm** [comment]
by changing the palette global variable it is configurable but I don't see the need of letting users change colours. If you don't like a them just choose another one, no?

**Comment by chrisbra** [comment]
I just want to give users being used to the current theme the possibility to keep on using those colors. Taste is a very individual thing....

**Comment by chrisbra** [comment]
But perhaps we should only do it if someone complains....

**Comment by Donearm** [comment]
Usually, that's what forks and issues are for :wink:

anyway, do you have an example of how to make the switch easy from the new to the old, and viceversa, with a global variable, perhaps? I admit I wouldn't know where to start to implement it

**Comment by chrisbra** [comment]
here we go: #162

**Pull request merged**
