### PR TITLE
delete badcat theme

### PR DESCRIPTION
**Pull request by kazukazuinaina**
Hi, Christian.
Look at this link.
> https://github.com/emanuelrosa/badcat/tree/master/autoload/airline/themes

I think `badcat` theme should remove this repo.
Could you check this Pull Request?

## Related PR

#200

### CODE REVIEW

**Comment by kazukazuinaina** [comment]
@chrisbra 
I want to merge this patch.
Is that okay?

**Comment by chrisbra** [comment]
thanks.

**Comment by kazukazuinaina** [comment]
Thanks for checking this Pull Request.

**Comment by r888800009** [comment]
I think this merge is destructive for this repo theme diversity and backward compatibility, you should add some information to prevent people waste time a lot of time to find this issue to fix the problem, maybe check the theme is removed from vim-airline-themes and show hint, or in document highlight how to find the upstream.

**Pull request merged**
