### PR TITLE
 Support light background in minimalist theme 

### PR DESCRIPTION
**Pull request by softmoth**

### CODE REVIEW

**Comment by dikiaap** [comment]
This gives me an error if I enable `let g:airline#extensions#tabline#enabled = 1`

img

**Comment by chrisbra** [comment]
> let s:want_showmod = get(g:, 'airline_minimalist_showmod', 0)

That needs to be documented.

**Comment by softmoth** [comment]
Thanks, I have updated the commit to document that setting.

**Comment by chrisbra** [comment]
thanks

**Pull request merged**
