### PR TITLE
Revert "base16-theme: Revert changes for active statusline"

### PR DESCRIPTION
**Pull request by blueyed**
This reverts commit 04f4b0f77863582bf3da42441d41220472c144a3.

### CODE REVIEW

**Comment by chrisbra** [comment]
What problem does this fix? Please squash into a single commit.

**Comment by diegs** [comment]
I believe this change messed up the status line for some base16 themes, including base16-ocean (which I'm using)

**Comment by blueyed** [comment]
Squashed..

I'm using a slightly changed `solarized` airline theme by now.

So I do not really care that much, but @diegs could check which commit breaks it (using `git bisect`), and if e.g. https://github.com/vim-airline/vim-airline/pull/893 by itself broke it.

**Comment by diegs** [comment]
I actually bisected it to a different issue (https://github.com/vim-airline/vim-airline/issues/1067). Thanks!

**Comment by chrisbra** [comment]
So what problem does this fix? I still don't understand what you are trying to fix here.

**Comment by blueyed** [comment]
@chrisbra 
See https://github.com/vim-airline/vim-airline/pull/948#issuecomment-184644276 and around.

Feel free to close it and not revert the revert - I just felt it's better to not use a different bg/style for the filename part with normal/focused windows.

**Comment by chrisbra** [comment]
I don't think we should change this now back. Some people seem to like this behaviour, other the old one. At the very least, this should be configurable but as the current solution I am not merging. Sorry.

**Pull request closed without merging**
