### PR TITLE
Added Deus Theme

### PR DESCRIPTION
**Pull request by ajmwagar**
I added an airline theme for the vim-deus color scheme. See [here](https://github.com/ajmwagar/vim-dues)  for more information.

### CODE REVIEW

**Comment by chrisbra** [comment]
please add the theme to the documentation.

**Comment by ajmwagar** [comment]
I added a screenshot on the vim-airline repo.

**Comment by fbearoff** [comment]
I've added deus to the documentation in PR https://github.com/vim-airline/vim-airline-themes/pull/98

**Comment by chrisbra** [comment]
closing in favor of #98

**Pull request closed without merging**
