### PR TITLE
delete escape character and update ci

### PR DESCRIPTION
**Pull request by kazukazuinaina**
This PR delete escape character and improving CI performance

### CODE REVIEW

**Comment by kazukazuinaina** [comment]
Would I merge this patch?

**Comment by chrisbra** [comment]
does that work correctly?

**Comment by kazukazuinaina** [comment]
I have checked the status of travis and these are working fine.
I think it works correctly.

> https://travis-ci.org/github/vim-airline/vim-airline-themes/builds/700057010

**Comment by chrisbra** [comment]
I guess this is okay then. Would probably make sense to use `norm!` instead of `norm`. Please go ahead and merge it.

**Comment by kazukazuinaina** [comment]
Thanks, Christian.
I changed it to use `normal!` instead of `normal`.

**Comment by kazukazuinaina** [comment]
This patch has merged.

Thank you for your review, Christian!

**Pull request merged**
