### PR TITLE
onedark.vim: Add 16-color support

### PR DESCRIPTION
**Pull request by joshdick**

### CODE REVIEW

**Comment by chrisbra** [comment]
please update the documentation as well.

**Comment by joshdick** [comment]
This theme is already mentioned in the documentation; not sure what there is to update?

**Comment by chrisbra** [comment]
The variable `onedark_termcolors` needs to be documented.

**Comment by joshdick** [comment]
Done.

**Comment by chrisbra** [comment]
thanks.

**Pull request merged**
