### PR TITLE
Tweak jellybeans for more readability, information

### PR DESCRIPTION
**Pull request by betaveros**
OK, a much smaller set of tweaks I wanted to see:

- darken green background of INSERT (to match original)
- restore orange modified highlight
- unify 2nd sections, deduplicate 3rd sections
- make sides of inactive bar brighter for better readability

I know this is largely a matter of taste, but hopefully these are reasonably uncontroversial. I think points 1 and 4 increase readability, point 2 adds information, point 3 is partly bookkeeping and partly changing the rather counterintuitive way the center sections brighten and the 2nd sections darken simultaneously when switching from Normal to anything else.

### CODE REVIEW

**Comment by chrisbra** [comment]
can you post a screenshot please?

**Comment by betaveros** [comment]
is this OK?
tweaked-jellybeans

**Comment by chrisbra** [comment]
So this is the new patched version? Can you also post a screenshot of the current non-patched version?

**Comment by betaveros** [comment]
jellybeans

**Comment by chrisbra** [comment]
thanks looks good.

**Pull request merged**
