### PR TITLE
Fix markdown in ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by kazukazuinaina**
I'm sorry...
I mistaked a bit about `ISSUE_TEMPLATE.md`'s markdown so I fixed.
Could you check this Pull Request?

### CODE REVIEW

**Comment by kazukazuinaina** [comment]
@chrisbra 

If you don't need this pull request, feel free to close it. 🙇

**Comment by kazukazuinaina** [comment]
ping🙇 @chrisbra

**Comment by chrisbra** [comment]
thanks, forgot about this one.

**Comment by kazukazuinaina** [comment]
Thank you for your confirmation while busy.

**Pull request merged**
